-- 1. SELEZIONARE TUTTI GLI INSEGNANTI
    SELECT *
    FROM `teachers`;
    -- totale (100)

-- 2. SELEIONARE TUTTI GLI STUDENTI IL CUI NOME INIZIA PER 'E' (CERCARE OPERATORI WILDCARD)
    SELECT *
    FROM `students`
    WHERE `name`
    LIKE 'E%';
    -- totale (373)

-- 3.SELEZIONARE TUTTI GLI STUDENTI CHE SI SONO ISCRITTI NEL 2021
    SELECT *
    FROM `students`
    WHERE `enrolment_date`
    BETWEEN '2021-01-01' AND '2021-12-31';
    -- totale (734)

-- 4. SELEZIONARE TUTTI I CORSI CHE NON HANNO UN SITO WEB (CERCARE GLI OPERATORI NULL/NOT NULL)
    SELECT *
    FROM `courses` 
    WHERE `website` IS NULL;
    -- totale (676)

-- 5. SELEZIONARE TUTTI GLI INSEGNANTI CHE HANNO UN NUMERO DI TELEFONO (CERCARE GLI OPERATORI NULL/NOT NULL)
    SELECT *
    FROM `teachers`
    WHERE `phone` IS NOT NULL;
    -- totale (50)

-- 6. SELEZIONARE TUTTI GLI APPELLI D'ESAME DEI MESI DI GIUGNO E LUGLIO
    SELECT *
    FROM `exams`
    WHERE `date` BETWEEN '2020-06-01' AND '2020-07-31';
    -- totale (2634)

-- 7. QUAL' E' IL NUMERO TOTALE DEGLI STUDENTI ISCRITTI
    SELECT *
    FROM `students`;
    -- totale (5000)